# Project
PROJECT_NAME_MAX_LENGTH = 200
PROJECT_STATUS_OPEN = "open"
PROJECT_STATUS_CLOSED = "closed"

# User
USER_NAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

# GitHub
GITHUB_DOMAIN = "github.com"
